# Generated by Django 4.1.3 on 2023-01-15 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_estoqueentrada_estoquesaida_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstoqueEntrada',
        ),
        migrations.DeleteModel(
            name='EstoqueSaida',
        ),
        migrations.CreateModel(
            name='StockInventary',
            fields=[
            ],
            options={
                'verbose_name': 'registro de inventário',
                'verbose_name_plural': 'registros de inventário',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockProduction',
            fields=[
            ],
            options={
                'verbose_name': 'registro de produção',
                'verbose_name_plural': 'registros de produção',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockSale',
            fields=[
            ],
            options={
                'verbose_name': 'registro de venda',
                'verbose_name_plural': 'registros de vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockService',
            fields=[
            ],
            options={
                'verbose_name': 'registro de serviço',
                'verbose_name_plural': 'registros de serviços',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
        migrations.CreateModel(
            name='StockShopping',
            fields=[
            ],
            options={
                'verbose_name': 'registro de compra',
                'verbose_name_plural': 'registros de compras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stock.estoque',),
        ),
    ]
