# Generated by Django 4.1.3 on 2023-01-17 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activation', '0006_alter_company_start_data'),
        ('stock', '0005_estoque_company_estoque_partner_estoque_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='activation.company'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='funcionario',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(blank=True, choices=[('E', 'entrada'), ('S', 'saida')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='tipo_movimento',
            field=models.CharField(blank=True, choices=[('V', 'VENDA'), ('S', 'SERVIÇO'), ('C', 'COMPRA'), ('P', 'PRODUÇÃO'), ('I', 'INVENTÁRIO')], max_length=1),
        ),
    ]
