# Generated by Django 4.1.3 on 2023-01-22 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_alter_company_start_data'),
        ('stock', '0006_alter_estoque_company_alter_estoque_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activation.company'),
        ),
    ]
