# Generated by Django 4.1.3 on 2022-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_tokenuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='company',
            name='type_company',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='MEI', max_length=3),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
