# Generated by Django 4.1.3 on 2023-01-14 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataform', '0011_alter_item_type_item'),
        ('activation', '0006_alter_company_start_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('moviment', models.CharField(blank=True, choices=[('E', 'ENTRADA'), ('S', 'SAIDA')], max_length=1)),
                ('type_moviment', models.CharField(blank=True, choices=[('V', 'VENDA'), ('S', 'SERVIÇO'), ('C', 'COMPRA'), ('P', 'PRODUÇÃO'), ('I', 'INVENTÁRIO')], max_length=1)),
                ('type_register', models.CharField(choices=[('1', 'Não Autorizado'), ('2', 'Pedido'), ('3', 'Troca'), ('4', 'Devolução'), ('5', 'Garantia'), ('6', 'Consignado')], default='2', max_length=1)),
                ('status', models.CharField(choices=[('1', 'Não Iniciado'), ('2', 'Em Aberto'), ('3', 'Finalizado')], default='2', max_length=1)),
                ('document', models.PositiveIntegerField(blank=True, null=True, verbose_name='documento')),
                ('identify', models.PositiveIntegerField(blank=True, null=True, verbose_name='identificador')),
                ('car', models.CharField(max_length=20, null=True, verbose_name='veiculo')),
                ('car_sign', models.CharField(max_length=20, null=True, verbose_name='placa')),
                ('car_chassis', models.CharField(max_length=20, null=True, verbose_name='chassi')),
                ('car_model', models.CharField(max_length=20, null=True, verbose_name='modelo')),
                ('car_fabricator', models.CharField(max_length=20, null=True, verbose_name='fabricante')),
                ('sector', models.CharField(max_length=20, null=True, verbose_name='setor')),
                ('machine', models.CharField(max_length=20, null=True, verbose_name='maquina')),
                ('shift', models.CharField(max_length=20, null=True, verbose_name='turno')),
                ('responsible', models.CharField(max_length=20, null=True, verbose_name='responsavel')),
                ('place', models.CharField(max_length=20, null=True, verbose_name='local')),
                ('shipping_company', models.CharField(max_length=20, null=True, verbose_name='transportadora')),
                ('value_amount', models.FloatField(null=True, verbose_name='valor total')),
                ('value_liquid', models.FloatField(null=True, verbose_name='valor liquido')),
                ('value_discount', models.FloatField(null=True, verbose_name='valor desconto')),
                ('value_add', models.FloatField(null=True, verbose_name='valor acrescimo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.partner')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TransactionItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataform.item')),
                ('stock_qtd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='transactions.transaction')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TransactionInventary',
            fields=[
            ],
            options={
                'verbose_name': 'registro inventário',
                'verbose_name_plural': 'registro inventário',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionProduction',
            fields=[
            ],
            options={
                'verbose_name': 'registro produção',
                'verbose_name_plural': 'registro produção',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionSale',
            fields=[
            ],
            options={
                'verbose_name': 'registro venda',
                'verbose_name_plural': 'registro venda',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionService',
            fields=[
            ],
            options={
                'verbose_name': 'registro serviço',
                'verbose_name_plural': 'registro serviço',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionShopping',
            fields=[
            ],
            options={
                'verbose_name': 'registro compra',
                'verbose_name_plural': 'registro compra',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transactions.transaction',),
        ),
    ]
