# Generated by Django 4.1.3 on 2023-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitems',
            name='account',
            field=models.CharField(max_length=20, null=True, verbose_name='conta contabil'),
        ),
        migrations.AddField(
            model_name='transactionitems',
            name='price_custom',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='transactionitems',
            name='price_term',
            field=models.FloatField(null=True),
        ),
    ]
