# Generated by Django 4.1.3 on 2023-01-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='transactionitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='transactionitems',
            name='transaction',
        ),
        migrations.DeleteModel(
            name='TransactionInventary',
        ),
        migrations.DeleteModel(
            name='TransactionProduction',
        ),
        migrations.DeleteModel(
            name='TransactionSale',
        ),
        migrations.DeleteModel(
            name='TransactionService',
        ),
        migrations.DeleteModel(
            name='TransactionShopping',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TransactionItems',
        ),
    ]
