# Generated by Django 4.1.3 on 2023-01-14 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactionitems_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionitems',
            name='stock_qtd',
        ),
        migrations.AddField(
            model_name='transactionitems',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='transactions.transaction'),
            preserve_default=False,
        ),
    ]
