# Generated by Django 4.1.3 on 2022-12-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activation', '0006_alter_company_start_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('document', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone1', models.CharField(max_length=20, null=True)),
                ('phone2', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_partners', models.CharField(choices=[('1', 'Cliente'), ('2', 'Fornecedor'), ('3', 'Transportadora'), ('4', 'Vendedor'), ('5', 'Funcionário')], default='1', max_length=1)),
                ('type_person', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='J', max_length=1)),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
        ),
    ]
