# Generated by Django 4.1.3 on 2023-01-07 00:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_alter_company_start_data'),
        ('plataform', '0002_alter_item_category_alter_item_un_med'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='agencia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='banco',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='cert_reservista',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='cnh',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='cnpj',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='compl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='conta',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='cpf',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='ctps',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='data_admissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partner',
            name='data_demissao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partner',
            name='data_nasc',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partner',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='insc_est',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='insc_mun',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='pis',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='pix',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='rg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='secao',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tipo_conta',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='tit_eleitor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='zona',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='PartnerSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.partnergroup'),
        ),
        migrations.AddField(
            model_name='partner',
            name='subgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.partnersubgroup'),
        ),
    ]
