# Generated by Django 4.1.3 on 2023-01-09 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0003_partner_address_partner_agencia_partner_banco_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('nickname',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='updated_at',
        ),
    ]
