# Generated by Django 4.1.3 on 2023-01-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0004_alter_partner_options_remove_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',)},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('title',)},
        ),
        migrations.AlterModelOptions(
            name='partnergroup',
            options={'ordering': ('group',)},
        ),
        migrations.AlterModelOptions(
            name='partnersubgroup',
            options={'ordering': ('subgroup',)},
        ),
        migrations.AlterModelOptions(
            name='unmed',
            options={'ordering': ('description',)},
        ),
    ]
