# Generated by Django 4.1.3 on 2023-01-10 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_alter_company_start_data'),
        ('plataform', '0005_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code_fab',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cst',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='dun',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ean',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gross_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lead_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lot_mult',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='master_pack',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='ncm',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='net_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_pack',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_qtd',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_seg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='reference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('markup', models.FloatField(null=True)),
                ('commission', models.FloatField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activation.company')),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='plataform.brand'),
        ),
    ]
