# Generated by Django 4.1.3 on 2023-01-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0006_item_code_fab_item_color_item_cst_item_dun_item_ean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='dun',
            new_name='code_dun',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ean',
            new_name='code_ean',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='custom',
            new_name='pack_master',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gross_weight',
            new_name='pack_sale',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='master_pack',
            new_name='price_custom',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='net_weight',
            new_name='weight_gross',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='open_balance',
            new_name='weight_net',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sale_pack',
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_qtd',
            field=models.FloatField(null=True),
        ),
    ]
