# Generated by Django 4.1.3 on 2023-01-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataform', '0009_alter_partner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
